// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Parallax",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Parallax",
            targets: ["AppModule"],
            bundleIdentifier: "com.leonardolarranaga.Parallax",
            teamIdentifier: "S2979MMU4H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .motion(purposeString: "Parallax needs Core Motion to create the parallax effect."),
                .camera(purposeString: "Parallax needs access to the camera to view your art in AR.")
            ],
            appCategory: .graphicsDesign
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
